---
- name: Upgrade all packages to the latest
  yum:
    name: '*'
    state: latest

- name: Install the yum-utils
  yum: 
    name: yum-utils
    state: present

- name: Add Docker repository for CentOS 7
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install Docker Packages for CentOS 7
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - python-docker
    - python3
    - python3-pip

- name: Install docker-compose
  ansible.builtin.command: curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose | chmod +x /usr/local/bin/docker-compose
  become: yes
  ignore_errors: yes

- name: Add execution in case the command above fails. 
  command: sudo chmod +x /usr/local/bin/docker-compose

- name: Create a docker directory if it does not exist
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes