---
- name: Create data directory
  file:
    path: /opt/nginx/
    state: directory
    owner: 200

- name: Pull Docker image 
     docker_image: 
       name: "{{ default_container_image }}" 
       source: pull

- name: Create containers 
     	docker_container: 
       		name: "{{ default_container_name }}{{ item }}" 
       		image: "{{ default_container_image }}" 
       		state: present 
     	with_sequence: count={{ create_containers }}

- name: Copy docker-compose.yml File
  copy: src=./docker-compose.yml dest=/opt/nginx/docker-compose.yml owner=root group=root

- name: Check if service status is running
  command: cd /opt/nginx/ && (docker-compose ps -q nginx || docker ps -q --no-trunc | grep $(docker-compose ps -q nginx))
  register: result

- name: DEBUG
  debug:
    var: result
    verbosity: 4

- name: Run docker-compose up -d
  command: docker-compose -f /opt/nginx/docker-compose.yml up -d
  when: result.stdout | length == 0